# permissions for end users to view webservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webservice-viewer-role
rules:
- apiGroups:
  - apps.ghaabor.io
  resources:
  - webservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.ghaabor.io
  resources:
  - webservices/status
  verbs:
  - get
