# permissions for end users to edit webservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webservice-editor-role
rules:
- apiGroups:
  - apps.ghaabor.io
  resources:
  - webservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.ghaabor.io
  resources:
  - webservices/status
  verbs:
  - get
